-- we can read Lua syntax here!
return {
    ["font_hinting"] = 2,
    ["font_size"] = 22,
    ["bookmarks"] = {
        [1] = {
            ["text"] = "how doesnt she tho",
            ["notes"] = "they could never do",
            ["page"] = "/body/DocFragment[22]/body/div/p[48]/span[1]/text().179",
            ["chapter"] = "Chapter 9",
            ["datetime"] = "2023-05-21 17:54:14",
            ["highlighted"] = true,
            ["pos0"] = "/body/DocFragment[22]/body/div/p[48]/span[1]/text().179",
            ["pos1"] = "/body/DocFragment[22]/body/div/p[48]/span[1]/text().198",
        },
        [2] = {
            ["text"] = "mare like¿¿ horse fucker ???",
            ["notes"] = "her powerful mare-like buttocks protruded, it struck him for the first time that she was beautiful.",
            ["page"] = "/body/DocFragment[22]/body/div/p[44]/span/text().820",
            ["chapter"] = "Chapter 9",
            ["datetime"] = "2023-05-21 13:50:48",
            ["highlighted"] = true,
            ["pos0"] = "/body/DocFragment[22]/body/div/p[44]/span/text().820",
            ["pos1"] = "/body/DocFragment[22]/body/div/p[44]/span/text().919",
        },
        [3] = {
            ["text"] = "Page 346 The problem was how to keep the wheels of industry turning without increasing the real wealth of the world. Goods must be produced, but they must not be distributed. And in practice the only way of achieving this was by continuous warfare. @ 2023-05-19 23:42:17",
            ["notes"] = "The problem was how to keep the wheels of industry turning without increasing the real wealth of the world. Goods must be produced, but they must not be distributed. And in practice the only way of achieving this was by continuous warfare.",
            ["page"] = "/body/DocFragment[22]/body/div/blockquote[17]/span/text().560",
            ["chapter"] = "Chapter 9",
            ["datetime"] = "2023-05-19 23:42:17",
            ["highlighted"] = true,
            ["pos0"] = "/body/DocFragment[22]/body/div/blockquote[17]/span/text().560",
            ["pos1"] = "/body/DocFragment[22]/body/div/blockquote[17]/span/text().799",
        },
        [4] = {
            ["text"] = "who does that",
            ["chapter"] = "Chapter 9",
            ["page"] = "/body/DocFragment[22]/body/div/p[12]/span/text().545",
            ["notes"] = "as one sometimes does with a book of which one knows that one will ultimately read and re-read every word, he opened it at a different place",
            ["pos0"] = "/body/DocFragment[22]/body/div/p[12]/span/text().545",
            ["datetime"] = "2023-05-19 19:56:02",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[22]/body/div/p[12]/span/text().685",
        },
        [5] = {
            ["text"] = "no, youre a pos",
            ["chapter"] = "Chapter 7",
            ["page"] = "/body/DocFragment[20]/body/div/p[19]/span/text().0",
            ["notes"] = "“Yes. But the real point of the story——”",
            ["pos0"] = "/body/DocFragment[20]/body/div/p[19]/span/text().0",
            ["datetime"] = "2023-05-19 15:47:08",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[20]/body/div/p[19]/span/text().40",
        },
        [6] = {
            ["text"] = "NO SHIT WTF",
            ["chapter"] = "Chapter 7",
            ["page"] = "/body/DocFragment[20]/body/div/p[15]/span/text().70",
            ["notes"] = "felt somewhat ashamed of himself",
            ["pos0"] = "/body/DocFragment[20]/body/div/p[15]/span/text().70",
            ["datetime"] = "2023-05-19 15:45:45",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[20]/body/div/p[15]/span/text().102",
        },
        [7] = {
            ["text"] = "reddit gf",
            ["chapter"] = "Chapter 5",
            ["page"] = "/body/DocFragment[18]/body/div/p[21]/span/text().0",
            ["notes"] = "“You’re only a rebel from the waist downwards,” he told her.\
She thought this brilliantly witty and flung her arms round him in delight.",
            ["pos0"] = "/body/DocFragment[18]/body/div/p[21]/span/text().0",
            ["datetime"] = "2023-05-19 15:34:44",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[18]/body/div/p[22]/span/text().75",
        },
        [8] = {
            ["text"] = "puking rn ",
            ["notes"] = "but felt that he had a right to",
            ["page"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
            ["chapter"] = "Chapter 4",
            ["pos0"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
            ["datetime"] = "2023-05-18 23:36:22",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[17]/body/div/p[17]/span/text().523",
        },
        [9] = {
            ["text"] = "girl, RUN",
            ["notes"] = "The girl laughed delightedly",
            ["page"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
            ["chapter"] = "Chapter 2",
            ["pos0"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
            ["datetime"] = "2023-05-18 22:29:11",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[15]/body/div/p[24]/span/text().28",
        },
        [10] = {
            ["text"] = "get standards smh",
            ["notes"] = "I couldn’t care less,” said the girl",
            ["page"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
            ["chapter"] = "Chapter 2",
            ["pos0"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
            ["datetime"] = "2023-05-18 22:27:29",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[15]/body/div/p[15]/span/text().37",
        },
        [11] = {
            ["text"] = "hmmmmm",
            ["notes"] = "Only five nights ago he had contemplated smashing her skull in with a cobblestone, but that was of no importance.",
            ["page"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
            ["datetime"] = "2023-05-18 22:12:34",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[14]/body/div/p[22]/span/text().550",
        },
        [12] = {
            ["text"] = "its a trap",
            ["notes"] = "I love you.",
            ["page"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
            ["datetime"] = "2023-05-18 22:10:04",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().11",
        },
        [13] = {
            ["text"] = "based",
            ["notes"] = "“Litre and half litre—that’s all we serve.",
            ["page"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
            ["chapter"] = "Chapter 8",
            ["pos0"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
            ["datetime"] = "2023-05-18 00:01:16",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[12]/body/div/p[26]/span/text().89",
        },
        [14] = {
            ["text"] = "she a milf ",
            ["notes"] = "When I saw her in the light she was quite an old woman, fifty years old at least.",
            ["page"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
            ["chapter"] = "Chapter 6",
            ["pos0"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
            ["datetime"] = "2023-05-17 23:18:04",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().81",
        },
        [15] = {
            ["text"] = "im puking rn wtf",
            ["notes"] = "would ravish her and cut her throat at the moment of climax. Better than before, moreover, he realized why it was that he hated her. He hated her because she was young and pretty and sexless, because he wanted to go to bed with her and would never do so, because round her sweet supple waist, which seemed to ask you to encircle it with your arm, there was only the odious scarlet sash, aggressive symbol of chastity.",
            ["page"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
            ["datetime"] = "2023-05-16 23:39:13",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[5]/body/div/p[34]/span[3]/text().311",
        },
        [16] = {
            ["text"] = "Page 13 Oceania @ 2023-05-14 23:36:07",
            ["notes"] = "Oceania",
            ["page"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
            ["datetime"] = "2023-05-14 23:36:07",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[5]/body/div/p[8]/span/text().90",
        },
        [17] = {
            ["text"] = "Page 12 London @ 2023-05-14 23:36:30",
            ["notes"] = "London",
            ["page"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
            ["datetime"] = "2023-05-14 23:36:30",
            ["highlighted"] = true,
            ["pos1"] = "/body/DocFragment[5]/body/div/p[7]/span/text().288",
        },
    },
    ["bookmarks_sorted"] = true,
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["nightmode_images"] = true,
    ["highlight"] = {
        [13] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 1",
                ["text"] = "Oceania",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[8]/span/text().90",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
                ["datetime"] = "2023-05-14 23:36:07",
            },
        },
        [31] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 1",
                ["text"] = "would ravish her and cut her throat at the moment of climax. Better than before, moreover, he realized why it was that he hated her. He hated her because she was young and pretty and sexless, because he wanted to go to bed with her and would never do so, because round her sweet supple waist, which seemed to ask you to encircle it with your arm, there was only the odious scarlet sash, aggressive symbol of chastity.",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[34]/span[3]/text().311",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
                ["datetime"] = "2023-05-16 23:39:13",
            },
        },
        [12] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 1",
                ["text"] = "London",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[7]/span/text().288",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
                ["datetime"] = "2023-05-14 23:36:30",
            },
        },
        [251] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 4",
                ["text"] = "but felt that he had a right to",
                ["pos1"] = "/body/DocFragment[17]/body/div/p[17]/span/text().523",
                ["pos0"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
                ["datetime"] = "2023-05-18 23:36:22",
            },
        },
        [215] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 2",
                ["text"] = "I couldn’t care less,” said the girl",
                ["pos1"] = "/body/DocFragment[15]/body/div/p[15]/span/text().37",
                ["pos0"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
                ["datetime"] = "2023-05-18 22:27:29",
            },
        },
        [197] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 1",
                ["text"] = "Only five nights ago he had contemplated smashing her skull in with a cobblestone, but that was of no importance.",
                ["pos1"] = "/body/DocFragment[14]/body/div/p[22]/span/text().550",
                ["pos0"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
                ["datetime"] = "2023-05-18 22:12:34",
            },
        },
        [194] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 1",
                ["text"] = "I love you.",
                ["pos1"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().11",
                ["pos0"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
                ["datetime"] = "2023-05-18 22:10:04",
            },
        },
        [394] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 9",
                ["datetime"] = "2023-05-21 13:50:48",
                ["text"] = "her powerful mare-like buttocks protruded, it struck him for the first time that she was beautiful.",
                ["pos0"] = "/body/DocFragment[22]/body/div/p[44]/span/text().820",
                ["pos1"] = "/body/DocFragment[22]/body/div/p[44]/span/text().919",
            },
        },
        [298] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 7",
                ["text"] = "“Yes. But the real point of the story——”",
                ["pos1"] = "/body/DocFragment[20]/body/div/p[19]/span/text().40",
                ["pos0"] = "/body/DocFragment[20]/body/div/p[19]/span/text().0",
                ["datetime"] = "2023-05-19 15:47:08",
            },
        },
        [297] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 7",
                ["text"] = "felt somewhat ashamed of himself",
                ["pos1"] = "/body/DocFragment[20]/body/div/p[15]/span/text().102",
                ["pos0"] = "/body/DocFragment[20]/body/div/p[15]/span/text().70",
                ["datetime"] = "2023-05-19 15:45:45",
            },
        },
        [280] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 5",
                ["text"] = "“You’re only a rebel from the waist downwards,” he told her.\
She thought this brilliantly witty and flung her arms round him in delight.",
                ["pos1"] = "/body/DocFragment[18]/body/div/p[22]/span/text().75",
                ["pos0"] = "/body/DocFragment[18]/body/div/p[21]/span/text().0",
                ["datetime"] = "2023-05-19 15:34:44",
            },
        },
        [336] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 9",
                ["text"] = "as one sometimes does with a book of which one knows that one will ultimately read and re-read every word, he opened it at a different place",
                ["pos1"] = "/body/DocFragment[22]/body/div/p[12]/span/text().685",
                ["pos0"] = "/body/DocFragment[22]/body/div/p[12]/span/text().545",
                ["datetime"] = "2023-05-19 19:56:02",
            },
        },
        [395] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 9",
                ["datetime"] = "2023-05-21 17:54:14",
                ["text"] = "they could never do",
                ["pos0"] = "/body/DocFragment[22]/body/div/p[48]/span[1]/text().179",
                ["pos1"] = "/body/DocFragment[22]/body/div/p[48]/span[1]/text().198",
            },
        },
        [217] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 2",
                ["text"] = "The girl laughed delightedly",
                ["pos1"] = "/body/DocFragment[15]/body/div/p[24]/span/text().28",
                ["pos0"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
                ["datetime"] = "2023-05-18 22:29:11",
            },
        },
        [125] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 6",
                ["text"] = "When I saw her in the light she was quite an old woman, fifty years old at least.",
                ["pos1"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().81",
                ["pos0"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
                ["datetime"] = "2023-05-17 23:18:04",
            },
        },
        [159] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 8",
                ["text"] = "“Litre and half litre—that’s all we serve.",
                ["pos1"] = "/body/DocFragment[12]/body/div/p[26]/span/text().89",
                ["pos0"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
                ["datetime"] = "2023-05-18 00:01:16",
            },
        },
        [346] = {
            [1] = {
                ["drawer"] = "lighten",
                ["chapter"] = "Chapter 9",
                ["datetime"] = "2023-05-19 23:42:17",
                ["text"] = "The problem was how to keep the wheels of industry turning without increasing the real wealth of the world. Goods must be produced, but they must not be distributed. And in practice the only way of achieving this was by continuous warfare.",
                ["pos0"] = "/body/DocFragment[22]/body/div/blockquote[17]/span/text().560",
                ["pos1"] = "/body/DocFragment[22]/body/div/blockquote[17]/span/text().799",
            },
        },
    },
    ["highlights_imported"] = true,
    ["last_xpointer"] = "/body/DocFragment[14]/body/div/p[20]/span/text().1110",
    ["copt_h_page_margins"] = {
        [2] = 10,
        [1] = 10,
    },
    ["copt_block_rendering_mode"] = 3,
    ["gamma_index"] = 15,
    ["copt_embedded_fonts"] = 1,
    ["copt_embedded_css"] = 1,
    ["font_family_fonts"] = {},
    ["toc_ticks_ignored_levels"] = {},
    ["copt_t_page_margin"] = 15,
    ["copt_b_page_margin"] = 15,
    ["copt_sync_t_b_page_margins"] = 0,
    ["css"] = "./data/epub.css",
    ["render_mode"] = 0,
    ["highlight_drawer"] = "lighten",
    ["copt_visible_pages"] = 1,
    ["header_font_face"] = "Noto Sans",
    ["copt_font_size"] = 22,
    ["summary"] = {
        ["status"] = "reading",
        ["modified"] = "2023-05-13",
    },
    ["preferred_dictionaries"] = {},
    ["copt_font_kerning"] = 3,
    ["doc_props"] = {
        ["title"] = "1984",
        ["language"] = "en",
        ["keywords"] = "Criticism\
Literature: Classics\
Dystopias\
London (England)\
Political fiction\
Philosophy\
Political\
Fiction\
Literary\
Science Fiction\
Science Fiction - General\
General\
Literature - Classics\
Classics\
Totalitarianism",
        ["authors"] = "George Orwell",
        ["series"] = "",
        ["description"] = "SUMMARY: Winston Smith lives in a society where the government controls people's lives every second of the day. Alone in his small, one-room apartment, Winston dreams of a better life. Is freedom from this life of suffering possible? There must be something that the Party cannot control - something like love, perhaps?",
    },
    ["stats"] = {
        ["md5"] = "3bf27d096ecf0545894bc1624da4ec60",
        ["title"] = "1984",
        ["language"] = "en",
        ["notes"] = 14,
        ["highlights"] = 3,
        ["authors"] = "George Orwell",
        ["series"] = "N/A",
        ["pages"] = 564,
    },
    ["doc_pages"] = 564,
    ["copt_line_spacing"] = 100,
    ["copt_font_gamma"] = 15,
    ["page_overlap_style"] = "dim",
    ["text_lang"] = "en-US",
    ["copt_status_line"] = 1,
    ["disable_fuzzy_search"] = false,
    ["percent_finished"] = 0.34751773049645,
    ["gamma"] = 1,
    ["word_spacing"] = {
        [2] = 75,
        [1] = 95,
    },
    ["word_expansion"] = 0,
    ["embedded_fonts"] = true,
    ["font_face"] = "Noto Serif",
    ["font_kerning"] = 3,
    ["embedded_css"] = true,
    ["font_base_weight"] = 0,
    ["smooth_scaling"] = false,
    ["cjk_width_scaling"] = 100,
    ["copt_smooth_scaling"] = 0,
    ["inverse_reading_order"] = false,
    ["readermenu_tab_index"] = 1,
    ["copt_word_expansion"] = 0,
    ["text_lang_embedded_langs"] = true,
    ["hyphenation"] = true,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["copt_rotation_mode"] = 0,
    ["floating_punctuation"] = 0,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_word_spacing"] = {
        [2] = 75,
        [1] = 95,
    },
    ["copt_view_mode"] = 0,
    ["config_panel_index"] = 1,
    ["visible_pages"] = 1,
    ["show_overlap_enable"] = false,
    ["partial_md5_checksum"] = "3bf27d096ecf0545894bc1624da4ec60",
    ["line_space_percent"] = 100,
    ["copt_font_hinting"] = 2,
    ["copt_font_base_weight"] = 0,
    ["hyph_force_algorithmic"] = false,
    ["render_dpi"] = 96,
    ["cre_dom_version"] = 20210904,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["hide_nonlinear_flows"] = false,
    ["rotation_mode"] = 0,
}
