-- we can read Lua syntax here!
return {
    ["bookmarks_version"] = 20200615,
    ["cre_dom_version"] = 20210904,
    ["highlight"] = {
        [13] = {
            [1] = {
                ["datetime"] = "2023-05-14 23:36:07",
                ["chapter"] = "Chapter 1",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[8]/span/text().90",
                ["drawer"] = "lighten",
                ["text"] = "Oceania",
            },
        },
        [31] = {
            [1] = {
                ["datetime"] = "2023-05-16 23:39:13",
                ["chapter"] = "Chapter 1",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[34]/span[3]/text().311",
                ["drawer"] = "lighten",
                ["text"] = "would ravish her and cut her throat at the moment of climax. Better than before, moreover, he realized why it was that he hated her. He hated her because she was young and pretty and sexless, because he wanted to go to bed with her and would never do so, because round her sweet supple waist, which seemed to ask you to encircle it with your arm, there was only the odious scarlet sash, aggressive symbol of chastity.",
            },
        },
        [12] = {
            [1] = {
                ["datetime"] = "2023-05-14 23:36:30",
                ["chapter"] = "Chapter 1",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[7]/span/text().288",
                ["drawer"] = "lighten",
                ["text"] = "London",
            },
        },
        [251] = {
            [1] = {
                ["datetime"] = "2023-05-18 23:36:22",
                ["chapter"] = "Chapter 4",
                ["pos0"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
                ["pos1"] = "/body/DocFragment[17]/body/div/p[17]/span/text().523",
                ["drawer"] = "lighten",
                ["text"] = "but felt that he had a right to",
            },
        },
        [159] = {
            [1] = {
                ["datetime"] = "2023-05-18 00:01:16",
                ["chapter"] = "Chapter 8",
                ["pos0"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
                ["pos1"] = "/body/DocFragment[12]/body/div/p[26]/span/text().89",
                ["drawer"] = "lighten",
                ["text"] = "“Litre and half litre—that’s all we serve.",
            },
        },
        [215] = {
            [1] = {
                ["datetime"] = "2023-05-18 22:27:29",
                ["chapter"] = "Chapter 2",
                ["pos0"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
                ["pos1"] = "/body/DocFragment[15]/body/div/p[15]/span/text().37",
                ["drawer"] = "lighten",
                ["text"] = "I couldn’t care less,” said the girl",
            },
        },
        [197] = {
            [1] = {
                ["datetime"] = "2023-05-18 22:12:34",
                ["chapter"] = "Chapter 1",
                ["pos0"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
                ["pos1"] = "/body/DocFragment[14]/body/div/p[22]/span/text().550",
                ["drawer"] = "lighten",
                ["text"] = "Only five nights ago he had contemplated smashing her skull in with a cobblestone, but that was of no importance.",
            },
        },
        [125] = {
            [1] = {
                ["datetime"] = "2023-05-17 23:18:04",
                ["chapter"] = "Chapter 6",
                ["pos0"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
                ["pos1"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().81",
                ["drawer"] = "lighten",
                ["text"] = "When I saw her in the light she was quite an old woman, fifty years old at least.",
            },
        },
        [194] = {
            [1] = {
                ["datetime"] = "2023-05-18 22:10:04",
                ["chapter"] = "Chapter 1",
                ["pos0"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
                ["pos1"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().11",
                ["drawer"] = "lighten",
                ["text"] = "I love you.",
            },
        },
        [217] = {
            [1] = {
                ["datetime"] = "2023-05-18 22:29:11",
                ["chapter"] = "Chapter 2",
                ["pos0"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
                ["pos1"] = "/body/DocFragment[15]/body/div/p[24]/span/text().28",
                ["drawer"] = "lighten",
                ["text"] = "The girl laughed delightedly",
            },
        },
    },
    ["highlights_imported"] = true,
    ["embedded_css"] = true,
    ["embedded_fonts"] = true,
    ["smooth_scaling"] = false,
    ["nightmode_images"] = true,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["readermenu_tab_index"] = 1,
    ["copt_block_rendering_mode"] = 3,
    ["gamma_index"] = 15,
    ["copt_embedded_css"] = 1,
    ["css"] = "./data/epub.css",
    ["copt_render_dpi"] = 96,
    ["toc_ticks_ignored_levels"] = {},
    ["font_family_fonts"] = {},
    ["copt_b_page_margin"] = 15,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_nightmode_images"] = 1,
    ["highlight_drawer"] = "lighten",
    ["summary"] = {
        ["status"] = "reading",
        ["modified"] = "2023-05-13",
    },
    ["preferred_dictionaries"] = {},
    ["copt_visible_pages"] = 1,
    ["stats"] = {
        ["highlights"] = 2,
        ["notes"] = 8,
        ["language"] = "en",
        ["series"] = "N/A",
        ["md5"] = "3bf27d096ecf0545894bc1624da4ec60",
        ["pages"] = 564,
        ["authors"] = "George Orwell",
        ["title"] = "1984",
    },
    ["doc_pages"] = 564,
    ["header_font_face"] = "Noto Sans",
    ["copt_font_size"] = 22,
    ["copt_font_base_weight"] = 0,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["copt_word_expansion"] = 0,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_line_spacing"] = 100,
    ["copt_font_gamma"] = 15,
    ["page_overlap_style"] = "dim",
    ["copt_status_line"] = 1,
    ["disable_fuzzy_search"] = false,
    ["text_lang"] = "en-US",
    ["percent_finished"] = 0.4822695035461,
    ["partial_md5_checksum"] = "3bf27d096ecf0545894bc1624da4ec60",
    ["gamma"] = 1,
    ["word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["word_expansion"] = 0,
    ["copt_embedded_fonts"] = 1,
    ["font_hinting"] = 2,
    ["last_xpointer"] = "/body/DocFragment[18]/body/div/p[7]/span/text().814",
    ["cjk_width_scaling"] = 100,
    ["floating_punctuation"] = 0,
    ["inverse_reading_order"] = false,
    ["hyph_force_algorithmic"] = false,
    ["render_mode"] = 0,
    ["font_size"] = 22,
    ["font_face"] = "Noto Serif",
    ["font_base_weight"] = 0,
    ["text_lang_embedded_langs"] = true,
    ["hyphenation"] = true,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["copt_rotation_mode"] = 0,
    ["line_space_percent"] = 100,
    ["rotation_mode"] = 0,
    ["visible_pages"] = 1,
    ["show_overlap_enable"] = false,
    ["doc_props"] = {
        ["authors"] = "George Orwell",
        ["series"] = "",
        ["description"] = "SUMMARY: Winston Smith lives in a society where the government controls people's lives every second of the day. Alone in his small, one-room apartment, Winston dreams of a better life. Is freedom from this life of suffering possible? There must be something that the Party cannot control - something like love, perhaps?",
        ["keywords"] = "Criticism\
Literature: Classics\
Dystopias\
London (England)\
Political fiction\
Philosophy\
Political\
Fiction\
Literary\
Science Fiction\
Science Fiction - General\
General\
Literature - Classics\
Classics\
Totalitarianism",
        ["language"] = "en",
        ["title"] = "1984",
    },
    ["copt_view_mode"] = 0,
    ["config_panel_index"] = 1,
    ["copt_t_page_margin"] = 15,
    ["hide_nonlinear_flows"] = false,
    ["render_dpi"] = 96,
    ["font_kerning"] = 3,
    ["bookmarks"] = {
        [1] = {
            ["datetime"] = "2023-05-18 23:36:22",
            ["text"] = "puking rn ",
            ["notes"] = "but felt that he had a right to",
            ["pos1"] = "/body/DocFragment[17]/body/div/p[17]/span/text().523",
            ["chapter"] = "Chapter 4",
            ["pos0"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
            ["page"] = "/body/DocFragment[17]/body/div/p[17]/span/text().492",
            ["highlighted"] = true,
        },
        [2] = {
            ["datetime"] = "2023-05-18 22:29:11",
            ["text"] = "girl, RUN",
            ["notes"] = "The girl laughed delightedly",
            ["pos1"] = "/body/DocFragment[15]/body/div/p[24]/span/text().28",
            ["chapter"] = "Chapter 2",
            ["pos0"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
            ["page"] = "/body/DocFragment[15]/body/div/p[24]/span/text().0",
            ["highlighted"] = true,
        },
        [3] = {
            ["datetime"] = "2023-05-18 22:27:29",
            ["text"] = "get standards smh",
            ["notes"] = "I couldn’t care less,” said the girl",
            ["pos1"] = "/body/DocFragment[15]/body/div/p[15]/span/text().37",
            ["chapter"] = "Chapter 2",
            ["pos0"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
            ["page"] = "/body/DocFragment[15]/body/div/p[15]/span/text().1",
            ["highlighted"] = true,
        },
        [4] = {
            ["datetime"] = "2023-05-18 22:12:34",
            ["text"] = "hmmmmm",
            ["notes"] = "Only five nights ago he had contemplated smashing her skull in with a cobblestone, but that was of no importance.",
            ["pos1"] = "/body/DocFragment[14]/body/div/p[22]/span/text().550",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
            ["page"] = "/body/DocFragment[14]/body/div/p[22]/span/text().437",
            ["highlighted"] = true,
        },
        [5] = {
            ["datetime"] = "2023-05-18 22:10:04",
            ["text"] = "its a trap",
            ["notes"] = "I love you.",
            ["pos1"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().11",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
            ["page"] = "/body/DocFragment[14]/body/div/p[18]/span/span/text().0",
            ["highlighted"] = true,
        },
        [6] = {
            ["datetime"] = "2023-05-18 00:01:16",
            ["text"] = "based",
            ["notes"] = "“Litre and half litre—that’s all we serve.",
            ["pos1"] = "/body/DocFragment[12]/body/div/p[26]/span/text().89",
            ["chapter"] = "Chapter 8",
            ["pos0"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
            ["page"] = "/body/DocFragment[12]/body/div/p[26]/span/text().47",
            ["highlighted"] = true,
        },
        [7] = {
            ["datetime"] = "2023-05-17 23:18:04",
            ["text"] = "she a milf ",
            ["notes"] = "When I saw her in the light she was quite an old woman, fifty years old at least.",
            ["pos1"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().81",
            ["chapter"] = "Chapter 6",
            ["pos0"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
            ["page"] = "/body/DocFragment[10]/body/div/p[22]/span[1]/span/text().0",
            ["highlighted"] = true,
        },
        [8] = {
            ["datetime"] = "2023-05-16 23:39:13",
            ["text"] = "im puking rn wtf",
            ["notes"] = "would ravish her and cut her throat at the moment of climax. Better than before, moreover, he realized why it was that he hated her. He hated her because she was young and pretty and sexless, because he wanted to go to bed with her and would never do so, because round her sweet supple waist, which seemed to ask you to encircle it with your arm, there was only the odious scarlet sash, aggressive symbol of chastity.",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[34]/span[3]/text().311",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
            ["page"] = "/body/DocFragment[5]/body/div/p[34]/span[1]/text().512",
            ["highlighted"] = true,
        },
        [9] = {
            ["datetime"] = "2023-05-14 23:36:07",
            ["text"] = "Page 13 Oceania @ 2023-05-14 23:36:07",
            ["notes"] = "Oceania",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[8]/span/text().90",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
            ["page"] = "/body/DocFragment[5]/body/div/p[8]/span/text().83",
            ["highlighted"] = true,
        },
        [10] = {
            ["datetime"] = "2023-05-14 23:36:30",
            ["text"] = "Page 12 London @ 2023-05-14 23:36:30",
            ["notes"] = "London",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[7]/span/text().288",
            ["chapter"] = "Chapter 1",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
            ["page"] = "/body/DocFragment[5]/body/div/p[7]/span/text().282",
            ["highlighted"] = true,
        },
    },
    ["bookmarks_sorted"] = true,
    ["bookmarks_sorted_20220106"] = true,
}
